version: alpha-0.0.1.{build}-{branch}

skip_commits:
  message: /\[ci skip\]/

clone_folder: C:\go-code\src\github.com\orange-lang\orange

install:
  - SET
  - set GOPATH=C:\go-code
  - set PATH=%PATH%;C:\go-code\bin
  - git submodule init
  - go get -t -v ./...

build_script:
  - go build 

test_script:
  - go test ./test/... -v 
