version: alpha-0.0.1.{build}-{branch}

skip_commits:
  message: /\[ci skip\]/

install:
  - SET
  - git submodule init
  - go get github.com/constabulary/gb/...
  - gb vendor restore 

build_script:
  - gb build 

test_script:
  - gb test -v 
